version: '3'
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    container_name: odoo
    user: root
    depends_on:
      - db
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=${HOSTNAME0}
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo.entrypoints=web, websecure
      - traefik.http.routers.odoo.rule=Host(`${HOSTNAME0}`) # || host0 to resolve the the host name
      - traefik.http.routers.odoo.tls.certresolver=production
      - traefik.http.routers.odoo.service=odoo
      - traefik.http.services.odoo.loadbalancer.server.port=${ODOO_PORT}
      - traefik.http.services.odoo.loadbalancer.server.port=${ODOO_LIVE_CHAT_PORT}
    restart: always             # run as a service
    